CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
id INTEGER(11)AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(30) NOT NULL,
devoured tinyint(1),
thedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

